# Generated by Django 3.2.8 on 2021-11-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('poster_path', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=500)),
                ('line', models.CharField(max_length=500)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('keywords', models.ManyToManyField(to='movies.Keyword')),
            ],
        ),
    ]
