# Generated by Django 3.2.8 on 2021-11-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='line',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
